# Generated by Django 4.1 on 2023-10-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviasales', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflight',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
